# Generated by Django 5.0.2 on 2024-03-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('genere', models.CharField(max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='upload/Albums/')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Emotion', models.CharField(choices=[('Angry', 'Angry'), ('Sad', 'Sad'), ('Happy', 'Happy'), ('Neutral', 'Neutral')], default='Neutral', max_length=10)),
                ('File', models.FileField(upload_to='uploads/Songs')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.album')),
            ],
        ),
    ]
