# Generated by Django 5.0.2 on 2024-03-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Album',
            new_name='album',
        ),
    ]
