# Generated by Django 5.0.2 on 2024-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_album_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Emotion',
            field=models.CharField(choices=[('Anger', 'Anger'), ('Sad', 'Sad'), ('Fear', 'Fear'), ('Surprise', 'Surprise'), ('Happy', 'Happy'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
    ]
