# Generated by Django 5.0.2 on 2024-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_song_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Favourited_by',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
