# Generated by Django 5.0.2 on 2024-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_album_favourited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Favourited_by',
            field=models.BooleanField(default=False),
        ),
    ]
